### ISSUE TITLE
HTML

### ISSUE THREAD

**Issue by zbichsel** [zbichsel/prework-study-guide#1]
# HTML

## User Story
As a bootcamp student
I want the prework notes to be structured on a webpage
so that I can easily find and read information

## Acceptance Criteria
GIVEN a Prework Study Guide website
WHEN I visit the website in my browser
THEN I see four boxes titled HTML, CSS, Git, and JavaScript with associated notes listed

**Comment by nasir-hussain-swat** [comment]
i have made this webpage for you i hope you will like it please check the pull request. and you can merge it.
